spring:
  #  数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/leon?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
  #  应用名称
  application:
    name: user
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  #  端口号
  port: 8888